language: node_js

node_js:
  - 10

jobs:
  include:
    - stage: test
      script: yarn test --bail --ci --colors
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: release
      node_js: lts/*
      deploy:
        on:
          all_branches: true
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
